# Generated by Django 5.2 on 2025-05-14 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(choices=[('GENERALISTE', 'Médecin généraliste'), ('PEDIATRIE', 'Pédiatrie'), ('CARDIOLOGIE', 'Cardiologie'), ('GYNECOLOGIE', 'Gynécologie'), ('INFIRMIER', 'Infirmier'), ('AUTRE', 'Autre')], max_length=50)),
                ('service', models.CharField(choices=[('URGENCE', 'Urgences'), ('CONSULTATION', 'Consultation externe'), ('HOSPITALISATION', 'Hospitalisation'), ('CHIRURGIE', 'Chirurgie'), ('LABORATOIRE', 'Laboratoire'), ('AUTRE', 'Autre')], max_length=50)),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('poste', models.CharField(blank=True, max_length=100)),
                ('date_recrutement', models.DateField(blank=True, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel de santé',
                'verbose_name_plural': 'Personnel de santé',
            },
        ),
    ]
