# Generated by Django 5.1.7 on 2025-05-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendezvous', models.IntegerField()),
                ('heure_arrivee', models.DateTimeField()),
                ('position', models.IntegerField()),
                ('en_cours', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField()),
                ('medecin', models.IntegerField()),
                ('date_rdv', models.DateTimeField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Confirmé', 'Confirmé'), ('Annulé', 'Annulé'), ('Terminé', 'Terminé')], default='En attente', max_length=20)),
                ('rappel_envoye', models.BooleanField(default=False)),
            ],
        ),
    ]
