# Generated by Django 5.1.7 on 2025-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents_medicaux', models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, null=True, verbose_name='Groupe sanguin')),
                ('rhésus', models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True)),
                ('taille', models.FloatField(blank=True, null=True, verbose_name='Taille (cm)')),
                ('poids', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('pression_artérielle', models.CharField(blank=True, max_length=7, null=True, verbose_name='Pression artérielle (ex: 12/8)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
            },
        ),
    ]
