# Generated by Django 5.1.7 on 2025-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('gravite', models.CharField(blank=True, choices=[('LEGER', 'Légère'), ('MODERE', 'Modérée'), ('GRAVE', 'Grave'), ('ANAPHYLACTIQUE', 'Anaphylactique')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type_antecedent', models.CharField(blank=True, choices=[('CHRONIQUE', 'Chronique'), ('AIGU', 'Aigu'), ('FAMILIAL', 'Familial'), ('HEREDITAIRE', 'Héréditaire')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('motif_consultation', models.CharField(max_length=255)),
                ('traitement_prescrit', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_hospitalisation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MesureClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('pression_arterielle', models.CharField(blank=True, choices=[('NORMALE', 'Normale'), ('HYPERTENSION_LEGERE', 'Hypertension légère'), ('HYPERTENSION_SEVERE', 'Hypertension sévère')], max_length=30, null=True)),
                ('date_mesure', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=100)),
                ('date_vaccination', models.DateField()),
                ('dose', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
