# Generated by Django 5.1.7 on 2025-05-16 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dossiers.dossiermedical'),
        ),
        migrations.AddField(
            model_name='antecedentmedical',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='dossiers.dossiermedical'),
        ),
        migrations.AddField(
            model_name='allergie',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='dossiers.dossiermedical'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='dossiers.dossiermedical'),
        ),
        migrations.AddField(
            model_name='mesureclinique',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='dossiers.dossiermedical'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dossiers.dossiermedical'),
        ),
    ]
