# Generated by Django 5.2 on 2025-05-12 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiermedical',
            options={'verbose_name': 'Dossier médical', 'verbose_name_plural': 'Dossiers médicaux'},
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='antecedents_medicaux',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='date_derniere_mise_a_jour',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='frequence_cardiaque',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='frequence_respiratoire',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='groupe_sanguin',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='notes_medicales',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='pression_arterielle',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='recommandations',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='rhésus',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='saturation_oxygene',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='temperature_corporelle',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='traitements_en_cours',
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('gravite', models.CharField(blank=True, choices=[('LEGER', 'Légère'), ('MODERE', 'Modérée'), ('GRAVE', 'Grave'), ('ANAPHYLACTIQUE', 'Anaphylactique')], max_length=20, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='dossiers.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type_antecedent', models.CharField(blank=True, choices=[('CHRONIQUE', 'Chronique'), ('AIGU', 'Aigu'), ('FAMILIAL', 'Familial'), ('HEREDITAIRE', 'Héréditaire')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='dossiers.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('motif_consultation', models.CharField(max_length=255)),
                ('traitement_prescrit', models.TextField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dossiers.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_hospitalisation', models.CharField(max_length=255)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='dossiers.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='MesureClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('pression_arterielle', models.CharField(blank=True, choices=[('NORMALE', 'Normale'), ('HYPERTENSION_LEGERE', 'Hypertension légère'), ('HYPERTENSION_SEVERE', 'Hypertension sévère')], max_length=30, null=True)),
                ('date_mesure', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='dossiers.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=100)),
                ('date_vaccination', models.DateField()),
                ('dose', models.CharField(blank=True, max_length=50, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dossiers.dossiermedical')),
            ],
        ),
    ]
